### ISSUE TITLE
Problema al generar una CURP especifica.

### ISSUE THREAD

**Issue by Javier1995** [prestigos/curp.js#4]
Tengo un verificador de CURP en un campo y  6 campos para generar una curp usando la curp.js, la cual realizo una comparación entre el generador y el campo de la Curp pero a la hora de hacer match no coinciden pero sin embargo, está registrado con la renapo.  Esta es la CURP que VEMM800814MCSLNR03 que causa conflicto en la curp.js. 

     
     function primerConsonante(str) {
    str = str.trim().substring(1).replace(/[AEIOU]/ig, '').substring(0, 1);
    return (str === '' || str === 'Ñ') ? 'X' : str;
       }

**Comment by chris-l** [comment]
Si, en efecto, era un bug que estaba afectando en ciertos casos los nombres. Ya esta solucionado, descarga la ultima version y prueba con esa.

Gracias!

**Comment by Javier1995** [comment]
Gracias a ti :)
