### ISSUE TITLE
Posible fallo en el script

### ISSUE THREAD

**Issue by SimonDice99** [prestigos/curp.js#5]
que tal buen dia 

primero que todo, agradecer por el script para generar CURP apegado a las normas oficiales, lo utilizo con fines de captura y para obtener la curp sin hacer uso de otros servicios en la nube para este fin.

me encontre con una situacion en la que las personas con un unico nombre propio y su nombre es "Jose" o "Maria" no me generaba la curp

agregue en la linea 248 la siguiente modificacion

linea Original
nombre_a_usar = comunes.indexOf(nombres[0]) > -1 ? nombres[1] : nombres[0];

Linea modificada
nombre_a_usar = comunes.indexOf(nombres[0]) > -1 ? (nombres.length > 1 ? nombres[1] : nombres[0] ) : nombres[0]; 

Saludos

**Comment by chris-l** [comment]
Resuelto en b5ebab6d309bb6e919bd2157c4140f7222331362.

Si el problema aun existe, necesitaría un ejemplo especifico.
